language: node_js
node_js:
- "8"
- node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Build doc
      node_js: node
      script: yarn run doc
    # - stage: Produce Coverage
    #   node_js: node
    #   script: yarn test:coveralls
